version: '3.9'
services:
  my-node-app:
    container_name: my-node-app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map host port to container port

  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27018:27017"  # Map host port to MongoDB container port